blog/urls.py
from django.urls import path
from .import views


urlpatterns = [
    path('signup', views.create_account, name="signup"),
    path('signin', views.user_login, name="login"),
    path('create_post', views.create_post, name="create-post"),
    path('logout', views.user_logout, name="logout"),
    path('all_post', views.all_post, name="all-post"),
    path('create_post', views.create_post, name="create-post"),
    path('detail_post/<int:post_id>', views.detail_post, name="detail-post"),
    path('create_comment/<int:post_id>', views.create_comment, name="create-comment"),
    path('delete/<int:post_id>', views.delete_post, name="delete-post"),
    path('all_users', views.all_users, name="all-users"),
    path('delete_user/<int:user_id>', views.delete_user, name="delete-user"),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  
from django.conf.urls.static import static  

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("blog.urls")),
]

if settings.DEBUG:  
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)  

blog/models.py
from django.db import models
from django.contrib.auth.models import User


class UserAccount(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50, null=False, blank=False)
    email = models.CharField(max_length=100, null=False, blank=False)
    
    def __str__(self):
        return self.first_name
    
class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField()
    image = models.ImageField()
    
    def __str__(self):
        return self.title
    
class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    posts = models.ForeignKey(Post, on_delete=models.CASCADE)
    comments = models.TextField()
    

blog/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.models import User
from .models import UserAccount, Post, Comment
from django.contrib.auth import authenticate, login, logout
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.contrib.auth.decorators import login_required


def create_account(request):
    if request.method == "POST":
        first_name = request.POST["firstname"]
        last_name = request.POST["lastname"]
        email = request.POST["email"]
        username = request.POST["username"]
        pass1 = request.POST["password1"]
        pass2 = request.POST["password2"]
        
        try:
            validate_email(email)
            if pass1 == pass2:
                if User.objects.filter(email=email).exists():
                    messages.info(request, 'Email exists..')
                    return render(request, 'create_account.html')
                else:
                    user = User.objects.create_user(username=email, password=pass1)
                    new_user = UserAccount()
                    new_user.user = user
                    new_user.first_name = first_name
                    new_user.last_name = last_name
                    new_user.email = email   
                    new_user.username = username             
                    new_user.save()
                    return redirect("login")
            else:
                messages.info(request, 'Password not matched..')
                return render(request, 'create_account.html')               
        except ValidationError as e:
            messages.info(request, 'Enter a valid e-mail address')
            return render(request, "create_account.html")
    else:
        return render(request, 'create_account.html')
    

def user_login(request):
    if request.method == "POST":
        email = request.POST["email"]
        password = request.POST["password"]
        
        try:
            validate_email(email)
            user = authenticate(username=email, password=password)

            if user is not None:
                login(request, user)
                return redirect("create-post")
            else:
                messages.info(request, 'Email or Password incorrect')
                return render(request, "login.html")
            
        except ValidationError as e:
            messages.info(request, 'Enter a valid e-mail address')
            return render(request, "login.html")
    context = {}
    return render(request, "login.html", context)


@login_required(login_url='/signin')
def create_post(request):   
    if request.method == "POST":       
        title = request.POST['title']
        description = request.POST['description']
        file = request.FILES['image']
        
        Post.objects.create(user=request.user, title=title, description=description, image=file)
        
        return redirect('all-post')            
    else:
        context = {}
        return render(request, 'create_post.html', context)  
    

def all_post(request):
    posts = Post.objects.all()
    print(request.user)
    context = {'posts': posts}
    return render(request, "all_post.html", context)


def detail_post(request, post_id):
    posts = Post.objects.get(id=post_id)
    comments = Comment.objects.filter(posts=posts.id)
    print(comments)
    context = {'posts': posts, 'comments': comments}
    return render(request, "detail_post.html", context)


@login_required(login_url='/signin')
def create_comment(request, post_id):
    if request.method=="POST":
        comment = request.POST['comment']
        
        post1 = Post.objects.get(id=post_id)

        new_comment = Comment()
        new_comment.comments = comment
        new_comment.user = request.user
        new_comment.posts = post1
        new_comment.save()
        return redirect('detail-post', post_id=post_id)
       
    posts = Post.objects.get(id=post_id)
    context = {'posts': posts}
    return render(request, "detail_post.html", context)


@login_required(login_url='/signin')
def delete_post(request, post_id):
    post = Post.objects.get(id=post_id)
    post.delete()
    return redirect("all-post")


@login_required(login_url='/signin')
def all_users(request): 
    users = UserAccount.objects.all()  
    context = {"users": users}
    return render(request, 'all_users.html', context)  


@login_required(login_url='/signin')
def delete_user(request, user_id): 
    user = UserAccount.objects.get(id=user_id)
    user.delete()
    return redirect("all-users")


def user_logout(request):
    logout(request)
    return redirect('login')
    
    

templates/all_post.html
{% extends 'base.html' %}

{% block content %}
</br>
{% for post in posts %}
<div class="left_image_right_news news_item wMFhj" style="margin-left: 30px;">
    <input type="image" src="{{ post.image.url }}" alt="Submit" width="100" height="100"></br>
    <a href="{% url 'detail-post' post.id %}">{{ post.title }}</a></br>
    {%if post.user == request.user %}
    <a class="btn btn-danger" href="delete/{{ post.id }}">Delete</a>
    {%endif %}
</div>
<hr>
</br>
{% endfor %}
{% endblock %}

templates/all_users.html
{% extends 'base.html' %}

{% block content %}

{% if request.user.is_staff %}   
<div class="card">
    <div class="card-header">Users List</div>
    <div class="card-body">
        <table class="table table-responsive-sm">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Full Name</th>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ user.first_name }}{{ " " }}{{ user.last_name }}</td>
                    <td>{{ user.username }}</td>
                    <td>{{ user.email }}</td>
                    <td>
                        <a class="btn btn-danger" href="delete_user/{{ user.id }}">Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endif %}   

{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Blog</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="nav-link" href="{% url 'all-post' %}">All Post <span class="sr-only">(current)</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        </ul>

        <ul class="navbar nav my-2 my-lg-0">
          
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout <span class="sr-only">(current)</span></a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login<span class="sr-only">(current)</span></a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

      {% block content %}
      
      {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/create_account.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="p-4 m-4">
        <div class="col-lg-5 mx-auto border rounded pt-4">
            <h3 class="alert alert-light border rounded">Create An Account</h3>
            <form action="/signup" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="">First name</label>
                    <input required type="text" name="firstname" id="" value="{{values.first_name}}" class="form-control form-control-sm" placeholder="Enter your first name">
                </div>
                <div class="form-group">
                    <label for="">Last name</label>
                    <input required type="text" name="lastname" id="" value="{{values.last_name}}" class="form-control form-control-sm" placeholder="Enter your last name">
                </div>
                <div class="form-group">
                    <label for="">Email</label>
                    <input required type="email" name="email" id="" value="{{values.email}}" class="form-control form-control-sm" placeholder="example@gmail.com">
                </div>
                <div class="form-group">
                    <label for="">Username</label>
                    <input required type="text" name="username" id="" value="{{values.username}}" class="form-control form-control-sm" placeholder="Enter your last name">
                </div>
                <div class="form-group">
                    <label for="">Password</label>
                    <input required type="password" name="password1" id="" class="form-control form-control-sm" placeholder="******">
                </div>
                <div class="form-group">
                    <label for="">Confirm Password</label>
                    <input required type="password" name="password2" id="" class="form-control form-control-sm" placeholder="******">
                </div>
                <div class="alert alert-danger" role="alert">
                    {% for message in messages %}
                    <p>{{ message }}</p>
                    {% endfor %}
                </div>
                <div class="form-group">
                    <input class="btn btn-sm btn-info" type="submit" value="Create An Account">
                </div>
      
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/create_post.html
{% extends 'base.html' %}

{% block content %}

<!doctype html>
<html lang="en">
   <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <title>Corsera</title>
   </head>
   <body>
      <div class="row">
         <div class="col-lg-2">
            <a href="/create_post" class="list-group-item list-group-item-action">Create Post</a>
            <a href="/all_post" class="list-group-item list-group-item-action">All Post</a> 
            {% if request.user.is_staff %}   
               <a href="{% url 'all-users' %}" class="list-group-item list-group-item-action">All Users</a>
            {% endif %}     
         </div>
         <div class="col-lg-5 mx-auto">
            <div class="row mx-auto mt-2"></div>
            <div class="card">
               <div class="card-header"><strong>Create Post</strong></div>
               <div class="card-body">
                  <div class="form-group">
                     <form action="/create_post" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}                        
                        <p>
                           <label for="id_title">Title:</label>
                           <input type="text" name="title" class="form-control" required id="id_title">
                        </p>
                        <p>
                           <label for="id_description">Description:</label>
                           <textarea name="description" cols="40" rows="10" class="form-control" id="id_description">
                           </textarea>
                        </p>
                        <div class="form-row field-image">
                            <div>
                               <label class="required" for="id_image">Image:</label>
                               <input type="file" name="image" accept="image/*" required="" id="id_image">
                            </div>
                         </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                     </form>
                  </div>
               </div>
            </div>
         </div>
      </div>
      </div>
      <!-- Optional JavaScript -->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
   </body>
</html>

{% endblock %}

templates/detail_post.html
{% extends 'base.html' %}

{% block content %}

<div class="col-md-12 col-lg-8 main-content">
  <img src="{{ posts.image.url }}" alt="Image" class="img-fluid mb-5" width="500" height="500">
    <div class="post-meta">
      <span class="author mr-2"><img src="{{ profile.image.url }}" alt="" class="mr-2">{{ profile.full_name }}</span>
      <span class="mr-2">{{ posts.date }}</span>
    </div>

  <h4>Title:</h4></br>
  <p class="mb-4">{{ posts.title }}</p>
  
  <div class="post-content-body">
    <h5>Description:</h5></br>
    <p>{{ posts.description }}</p>
  </br>
</div>
  <h5>Comments:</h5></br>
  {% for comment in comments %}
  <p>{{ comment.comments }}</p>
  <hr>
  {%endfor%}
  {% if user.is_authenticated %}
    <form action="/create_comment/{{ posts.id }}" method="POST">
      {% csrf_token %} 
      <b><label for="comment">Write comment:</label></b></br>
      <textarea id="comment" name="comment" rows="4" cols="50"></textarea>
      <br>
      <input type="submit" value="Submit">
    </form>
  {%else%}
    <div>
      <div class="story-meta-data sONJ0"><time class="published-time fw8bp">You must be logged in to post a comment.</time></div>
    </div>
  {%endif%}
  </br>
</div>

{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="p-4 m-4">
        <div class="col-lg-4 mt-4 mb-4 mx-auto border rounded pt-4">
            <h3 class="alert alert-light border mt-4 mb-4 rounded">Login Here</h3>
            <form action="" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="">Email</label>
                    <input required type="email" name="email" id="" class="form-control form-control-sm" placeholder="example@gmail.com">
                </div>
                <div class="form-group">
                    <label for="">Password</label>
                    <input required type="password" name="password" id="" class="form-control form-control-sm" placeholder="******">
                </div>
                    {% for message in messages %}
                     <div class="alert alert-danger" role="alert">
                    
                    <p>{{ message }}</p>
                </div>
                    {% endfor %}
                
                <div class="form-group">
                    <input class="btn btn-sm btn-info col-lg-3" type="submit" value="Login"><br>
                    <a>have no account?</a>
                    <a class="nav-link" href="{% url 'signup' %}">Signup <span class="sr-only">(current)</span></a>
                </div>
      
            </form>
        </div>
    </div>
</div>

{% endblock %}